### ISSUE TITLE
预览文件前端报错

### ISSUE THREAD

**Issue by GaodYang** [Jarrettluo/document-sharing-site#19]
docker-compose部署后，预览doc文件前端报错：
chunk-2d217155.8820db10.js:1  Uncaught (in promise) Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    at h.readEndOfCentral (chunk-2d217155.8820db10.js:1:38821)
    at h.load (chunk-2d217155.8820db10.js:1:40469)
    at chunk-2d217155.8820db10.js:1:11553

**Comment by Jarrettluo** [comment]
目前只支持docx文件
